### ISSUE TITLE
BUG: list doesn't update when decreasing threshold

### ISSUE THREAD

**Issue by Ahacad** [sinchang/vstar#19]
The repo list will not update if you decrease the threshold. 
This happens because: the data is fetched once and stored in sessionstorage (repos that satisfy the threshold only), and now if you decrease the threshold data won't be fetched again since you got a hit in the storage, so repos with stars lower than the threshold will not be fetched at all.
Of course, this can be got around by requesting another GitHub name and then come back, but that would be redundant.
You should change some logic when firstly fetching the data, for example, preserve the array before filtering rather than afterward.

**Comment by sinchang** [comment]
@Ahacad Thanks for your reporting. It was resolved.
