### ISSUE TITLE
The result is inaccurate

### ISSUE THREAD

**Issue by egoist** [sinchang/vstar#3]
<img width="471" alt="2017-03-18 4 37 51" src="https://cloud.githubusercontent.com/assets/8784712/24070484/50b55b2e-0bf9-11e7-8b3d-ef272c477f51.png">

some repos are missing, for example: egoist/hack

**Comment by sinchang** [comment]
@egoist sorry, I fixed it already.

**Comment by egoist** [comment]
nice, works like a charm now 😘
